=== nasa/Common-Metadata-Repository/schemas/resources/schemas/config/v0.0.1/schema.json
{
   "$id": "https://earthdata.nasa.gov/schema/generics/config",
   "$schema": "http://json-schema.org/draft-07/schema#",
   "title": "Generic-Config",
   "description": "This scheme defines how index configurations are to be defined. These index definitions support both Elastic and Graph-DB",
   "type": "object",
   "additionalProperties": false,
   "properties": {
        "MetadataSpecification": {
            "description": "Contains several fields to define the specifics of the grid",
            "$ref": "#/definitions/MetadataSpecificationType"},
        "SubConceptType": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4
        },
        "Generic": {"$ref": "#/definitions/GenericType"},
        "IndexSetup" : {
          "description": "Contains fields for index level configurations in Elastic",
          "$ref": "#/definitions/IndexSetupType"
        },
        "IndexConfiguration" : {
          "description": "Contains fields related to how Indexes should be processed when creating the elastic document.",
          "$ref": "#/definitions/IndexConfigurationType"
        },
        "Indexes": {
            "description": "A list of indexes to be added to the elastic document.",
            "type": "array",
            "uniqueItems": true,
            "minItems": 1,
            "items": {"$ref": "#/definitions/IndexType"}
        },
        "Validations": {
            "type": "array",
            "uniqueItems": true,
            "minItems": 1,
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "Fields": {
                        "description": "The field to validate, defined as a jq style path",
                        "type": "array",
                        "items": {
                            "type": "string",
                            "examples": [".RootElement.SubElement"],
                            "minLength": 1
                        },
                        "minItems": 1
                    },
                    "ValidationType": {
                        "description": "The type of validation to perform on the field",
                        "type": "string",
                        "enum": ["unique" ,"regex", "length", "value"],
                        "default": "regex"
                    },
                    "ValidationValue": {
                        "$comment": "This is the value to validate against. The type of value depends on the ValidationType.",
                        "type": ["string", "number"]
                    }
                },
                "required": ["Fields", "ValidationType"]
            }
        }
    },
    "required": ["MetadataSpecification", "Generic"],
    "definitions": {
        "MetadataSpecificationType": {
            "type": "object",
            "additionalProperties": false,
            "description": "This object requires any metadata record that is validated by this schema to provide information about the schema.",
            "properties": {
                "URL": {
                    "description": "This element represents the URL where the schema lives. The schema can be downloaded.",
                    "type": "string",
                    "const": "https://cdn.earthdata.nasa.gov/generic/config/v0.0.1"
                },
                "Name": {
                    "description": "This element represents the name of the schema.",
                    "type": "string",
                    "const": "Generic-Config"
                },
                "Version": {
                    "description": "This element represents the version of the schema.",
                    "type": "string",
                    "const": "0.0.1"
                }
            },
            "required": ["URL", "Name", "Version"]
        },
        "GenericType": {
          "type": "object",
          "additionalProperties": false,
          "Description": "The matching schema for this index configuration",
          "properties": {
            "Name": {"type": "string"},
            "Version": {"type": "string"}
          },
          "required": ["Name", "Version"]
        },
        "IndexSetupType": {
          "description": "Define Elastic configurations for the entire index. Changes here will affect lucine",
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "index" : {
              "description": "Settings passed along directly to lucine",
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "number_of_shards" : {
                  "type": "number",
                  "minimum": 1,
                  "maximum": 32
                },
                "number_of_replicas" : {
                  "type": "number",
                  "minimum": 1,
                  "maximum": 32
                },
                "refresh_interval" : {
                  "type": "string",
                  "pattern": "[0-9]+s"
                }
              }
            }
          }
        },
        "IndexConfigurationType": {
          "description": "CMR Settings (not Elastic settings) to use while parsing and handling the index list",
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "AllowAppending" :{
              "description": "true means that indexes with the same name will be appended, not overwritten",
              "type": "boolean"
            },
            "AdditionalKeywords": {
              "description": "A list of simple, top level fields to be added to the keyword (freetext)",
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              },
              "minItems": 1
            },
            "IndexName" : {
              "description": "This is the name of the Elastic Index when the default is not to be used, change this when you need to change the type of an existing index.",
              "type": "string",
              "example": "1_generic_service_draft",
              "pattern": "^[0-9]+_generic_[0-9a-z_]+$",
              "minimum": 1,
              "maximum": 64
            },
            "IndexNameForRevisions" : {
              "description": "This is the name of the Elastic Index, for storing multiple revisions, when the default is not to be used, change this when you need to change the type of an existing index.",
              "type": "string",
              "example": "1_all_generic_service_draft_revisions",
              "pattern": "^[0-9]+_all_generic_[0-9a-z_]+_revisions$",
              "minimum": 1,
              "maximum": 64
            }
          }
        },
        "IndexType": {
            "$comment": "This object is subject to major change",
            "type": "object",
            "additionalProperties": false,
            "description": "Define one index that needs to be created",
            "properties": {
                "Description": {
                    "description": "Note about the setting",
                    "type": "string",
                    "minLength": 1
                },
                "Field": {
                    "description": "The Field to index, defined as a jq style path",
                    "type": "string",
                    "examples": [".RootElement.SubElement"],
                    "minLength": 1
                },
                "Mapping": {
                  "description": "The data format to map this index to. string is of type 'keyword', and 'token' is the same as string but uses a 'whitespace' analyzer meaning each word can be found.",
                  "type": "string",
                  "default": "string",
                  "enum": ["date", "int", "string", "token"]
                },
                "Type": {
                    "description": "target index software to host the index",
                    "type": "string",
                    "enum": ["elastic", "graph"],
                    "default": "elastic"
                },
                "Name": {
                    "description": "The name to give the index within the index server",
                    "type": "string",
                    "minLength": 1
                },
                "Indexer": {
                    "description": "The name of the function in code that will generate the index for this field",
                    "type": "string",
                    "minLength": 1
                },
                "Configuration": {
                    "decription": "Any valid JSON can be defined here and it will be passed to the indexer as a configuration for this specific index",
                    "additionalProperties": true
                }
            },
            "required": ["Field", "Name"]
        }
    }
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/grid/v0.0.1/config.json
{
  "MetadataSpecification": {
      "URL": "https://cdn.earthdata.nasa.gov/generic/config/v0.0.1",
      "Name": "Generic-Config",
      "Version": "0.0.1"
  },
    "Generic": {
      "Name": "Grid",
      "Version": "0.0.1"
    },
  "SubConceptType": "GRD",
  "Indexes":
  [
    {
       "Description": "Name",
       "Field": ".Name",
       "Name": "Name",
       "Mapping": "string"
    },
    {
      "Description": "Long Name",
      "Field": ".LongName",
      "Name": "Long-Name",
      "Mapping": "string"
    },
    {
      "Description": "Description of the Grid",
      "Field": ".Description",
      "Name": "Description",
      "Mapping": "string"
    },
    {
      "Description": "Coordinate Reference System Type",
      "Field": ".GridDefinition.CoordinateReferenceSystemID.Type",
      "Name": "CoordinateReferenceSystemID-Type",
      "Mapping": "string"
    },
    {
      "Description": "Coordinate Reference System Code",
      "Field": ".GridDefinition.CoordinateReferenceSystemID.Code",
      "Name": "CoordinateReferenceSystemID-Code",
      "Mapping": "string"
    },
    {
      "Description": "Coordinate Reference System Title",
      "Field": ".GridDefinition.CoordinateReferenceSystemID.Title",
      "Name": "CoordinateReferenceSystemID-Title",
      "Mapping": "string"
    },
    {
      "Description": "Coordinate Reference System URL",
      "Field": ".GridDefinition.CoordinateReferenceSystemID.URL",
      "Name": "CoordinateReferenceSystemID-URL",
      "Mapping": "string"
    },
    {
      "Description": "Coordinate Reference System",
      "Field": ".GridDefinition.CoordinateReferenceSystemID",
      "Name": "CoordinateReferenceSystem",
      "Mapping": "string",
      "Indexer": "complex-field",
      "Configuration": {"sub-fields": ["Type", "Code", "Title", "URL"]}
    },
    {
      "Description": "Mock index for property field",
      "Field": ".Name",
      "Name": "Name",
      "Type": "graph",
      "Indexer": "property"
  },
  {
      "Description": "Mock index for property field",
      "Field": ".Version",
      "Name": "Version",
      "Type": "graph",
      "Indexer": "property"
  },
  {
      "Description": "Mock index for separate entity field",
      "Field": ".GridDefinition.CoordinateReferenceSystemID",
      "Name": "CoordinateReferenceSystem",
      "Type": "graph",
      "Indexer": "separate-node",
      "Configuration": {
          "properties": ["Type", "URL"],
          "relationship": "DefinedBy"
          }
  },
  {
      "Description": "Mock index for separate entity field",
      "Field": ".Organization",
      "Name": "Organization",
      "Type": "graph",
      "Indexer": "separate-node",
      "Configuration": {
          "properties": ["ShortName"],
          "relationship": "PublishedBy"
          }
  },
  {
      "Description": "Mock index for separate entity field",
      "Field": ".RelatedURLs",
      "Name": "URL",
      "Type": "graph",
      "Indexer": "separate-node",
      "Configuration": {
          "properties": ["URL", "URLContentType"],
          "relationship": "RelatedTo"
          }
  }
  ]
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/data-quality-summary/v1.0.0/config.json
{
  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generic/config/v0.0.1",
    "Name": "Generic-Config",
    "Version": "0.0.1"
  },
  "Generic": {
    "Name": "Data Quality Summary",
    "Version": "1.0.0"
  },
  "SubConceptType": "DQS",
  "IndexSetup" : {
    "index": {
      "number_of_shards": 3,
      "number_of_replicas": 1,
      "refresh_interval": "1s"
    }
  },
  "IndexConfiguration": {
    "IndexName": "2_generic_data_quality_summary",
    "IndexNameForRevisions": "2_all_generic_data_quality_summary_revisions"
  },
 "Indexes":
  [
    {
      "Description": "Name",
      "Field": ".Name",
      "Name": "Name",
      "Mapping": "string"
    },
    {
      "Description": "Id - This is the old ECHO 10 GUID.",
      "Field": ".Id",
      "Name": "Id",
      "Mapping": "string"
    }
  ]
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/service-entry/v1.0.0/config.json
{
  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generic/config/v0.0.1",
    "Name": "Generic-Config",
    "Version": "0.0.1"
  },
  "Generic": {
    "Name": "Service Entry",
    "Version": "1.0.0"
  },
  "SubConceptType": "SE",
  "IndexConfiguration": {
    "IndexName": "2_generic_service_entry",
    "IndexNameForRevisions": "2_all_generic_service_entry_revisions"
  },
  "Indexes":
  [
    {
      "Description": "Name",
      "Field": ".Name",
      "Name": "Name",
      "Mapping": "string"
    }, {
      "Description": "Id - This is the old ECHO 10 GUID.",
      "Field": ".Id",
      "Name": "Id",
      "Mapping": "string"
    }
  ]
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/data-quality-summary-draft/v1.0.0/config.json
{
  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generic/config/v0.0.1",
    "Name": "Generic-Config",
    "Version": "0.0.1"
  },
  "Generic": {
    "Name": "Data Quality Summary Draft",
    "Version": "1.0.0"
  },
  "SubConceptType": "DQD",
  "IndexSetup" : {
    "index": {
      "number_of_shards": 3,
      "number_of_replicas": 1,
      "refresh_interval": "1s"
    }
  },
  "Indexes":
  [
    {
      "Description": "Draft Data Quality Summary Name",
      "Field": ".Name",
      "Name": "name",
      "Mapping": "string"
    }
  ]
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/collection-draft/v1.0.0/config.json
{
  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generic/config/v0.0.1",
    "Name": "Generic-Config",
    "Version": "0.0.1"
  },
  "Generic": {
    "Name": "Collection Draft",
    "Version": "1.0.0"
  },
  "SubConceptType": "CD",
  "IndexSetup" : {
    "index": {
      "number_of_shards": 3,
      "number_of_replicas": 1,
      "refresh_interval": "1s"
    }
  },
  "Indexes":
  [
    {
      "Description": "Draft Collection Short Name",
      "Field": ".ShortName",
      "Name": "name",
      "Mapping": "string"
    },
    {
      "Description": "Draft Collection Project short names.",
      "Field": ".Projects",
      "Name": "project",
      "Mapping": "string",
      "Indexer": "simple-array-field",
      "Configuration": {"sub-fields": ["ShortName"]}
    },
    {
      "Description": "Draft Collection Platform short names.",
      "Field": ".Platforms",
      "Name": "platform",
      "Mapping": "string",
      "Indexer": "simple-array-field",
      "Configuration": {"sub-fields": ["ShortName"]}
    }
  ]
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/citation-draft/v1.0.0/config.json
{
  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generic/config/v0.0.1",
    "Name": "Generic-Config",
    "Version": "0.0.1"
  },
  "Generic": {
    "Name": "Citation Draft",
    "Version": "1.0.0"
  },
  "SubConceptType": "CITD",
  "IndexSetup" : {
    "index": {
      "number_of_shards": 3,
      "number_of_replicas": 1,
      "refresh_interval": "1s"
    }
  },
  "IndexConfiguration": {
    "IndexName": "2_generic_citation_draft",
    "IndexNameForRevisions": "2_all_generic_citation_draft_revisions"
  },

  "Indexes":
  [
    {
      "Description": "Draft Citation Short Name",
      "Field": ".Name",
      "Name": "name",
      "Mapping": "string"
    }
  ]
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/service-draft/v1.0.0/config.json
{
  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generic/config/v0.0.1",
    "Name": "Generic-Config",
    "Version": "0.0.1"
  },
  "Generic": {
    "Name": "Service Draft",
    "Version": "1.0.0"
  },
  "SubConceptType": "SD",
  "IndexSetup" : {
    "index": {
      "number_of_shards": 3,
      "number_of_replicas": 1,
      "refresh_interval": "1s"
    }
  },
  "Indexes":
  [
    {
      "Description": "Draft Service Name",
      "Field": ".Name",
      "Name": "name",
      "Mapping": "string"
    }
  ]
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/order-option/v1.0.0/config.json
{
  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generic/config/v0.0.1",
    "Name": "Generic-Config",
    "Version": "0.0.1"
  },
  "Generic": {
    "Name": "Order Option",
    "Version": "1.0.0"
  },
  "SubConceptType": "OO",
  "IndexConfiguration": {
    "IndexName": "2_generic_order_option",
    "IndexNameForRevisions": "2_all_generic_order_option_revisions"
  },
  "Indexes":
  [
    {
      "Description": "Name",
      "Field": ".Name",
      "Name": "Name",
      "Mapping": "string"
    }, {
      "Description": "Id - This is the old ECHO 10 GUID.",
      "Field": ".Id",
      "Name": "Id",
      "Mapping": "string"
    }
  ]
}
