=== nasa/Common-Metadata-Repository/schemas/resources/schemas/visualization/v1.0.0/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "UMM-Vis",
  "type": "object",
  "additionalProperties": false,

  "properties": {
    "Identifier": {
      "description": "The unique identifier for the visualization.",
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },
    "Name": {
      "description": "A name of the visualization.",
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },
    "Title": {
      "description": "A short descriptive title of the visualization.",
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },
    "Subtitle": {
      "description": "A short descriptive subtitle of the visualization.",
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },
    "Description": {
      "description": "A human readable description of the visualization written using HTML notation for advanced text.  The goal is to create descriptions for the science-minded public that may have an interest in finding out what the visualization shows, why itâ€™s important, how it was created, etc...",
      "type": "string",
      "minLength": 1,
      "maxLength": 1024
    },

    "ScienceKeywords": {
      "description": "Earth Science keywords that are representative of the data being visualized. The controlled vocabulary for Science Keywords is maintained in the Keyword Management System (KMS).",
      "type": "array",
      "items": {
        "$ref": "#/definitions/ScienceKeywordType"
      },
      "minItems": 1
    },

    "SpatialExtent": {
      "$ref": "spatial-temporal-extent.json#/definitions/SpatialExtentType"
    },

    "TemporalExtents": {
      "description": "This class contains attributes which describe the temporal range of a specific layer. Temporal Extent includes a specification of the Temporal Range Type of the collection, which is one of Range Date Time, Single Date Time, or Periodic Date Time",
      "type": "array",
      "items": {
        "$ref": "spatial-temporal-extent.json#/definitions/TemporalExtentType"
      },
      "minItems": 1
    },

    "ConceptIds": {
      "description": "Which CMR dataset(s) are represented by the visualization.",
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "type": {
            "description": "Identify whether the associated dataset is NRT or STD.",
            "type": "string",
            "enum": [
              "NRT",
              "STD"
            ]
          },
          "value": {
            "description": "The dataset's CMR concept id",
            "type": "string"
          },
          "dataCenter": {
            "type": "string"
          },
          "shortName": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "version": {
            "type": "string"
          }
        },
        "required": ["type", "value"]
      },
      "minItems": 1
    },

    "VisualizationType": {
       "type": "string",
       "enum": ["tiles", "maps"]
    },

    "MetadataSpecification": {
      "description": "Required to add in schema information into every record. It includes the schema's name, version, and URL location. The information is controlled through enumerations at the end of this schema.",
      "$ref": "#/definitions/MetadataSpecificationType"
    },

    "What": {
      "$comment": "must be here when additionalProperties==false. otherwise fails"
    },

    "How": {
      "$comment": "must be here when additionalProperties==false. otherwise fails"
    }
  },
  "required": [
    "Identifier",
    "Name",
    "VisualizationType",
    "What",
    "How",
    "ConceptIds", 
    "MetadataSpecification"
  ],  

  "allOf": [
    {
      "if": {
        "properties": {
          "VisualizationType": {"const": "tiles"}
        }
      },
      "then": {
        "properties": {
          "What": {
            "$ref": "umm-vis-tiles-schema.json#/definitions/What"
          },
          "How": {
            "$ref": "umm-vis-tiles-schema.json#/definitions/How"
          }
        }
      }
    },

    {
      "if": {
        "properties": {
          "VisualizationType": {"const": "maps"}
        }
      },
      "then": {
        "properties": {
          "What": {
            "$ref": "umm-vis-maps-schema.json#/definitions/What"
          },
          "How": {
            "$ref": "umm-vis-maps-schema.json#/definitions/How"
          }
        }
      }
    }
  ],

  "definitions": {

    "ScienceKeywordType": {
      "type": "object",
      "additionalProperties": false,
      "description": "Enables specification of Earth science keywords related to the collection.  The Earth Science keywords are chosen from a controlled keyword hierarchy maintained in the Keyword Management System (KMS). The valid values can be found at the KMS website: https://gcmdservices.gsfc.nasa.gov/kms/concepts/concept_scheme/sciencekeywords?format=csv.",
      "properties": {
        "Category": {
         "$ref": "#/definitions/KeywordStringType"
        },
        "Topic": {
          "$ref": "#/definitions/KeywordStringType"
        },
        "Term": {
          "$ref": "#/definitions/KeywordStringType"
        },
        "VariableLevel1": {
          "$ref": "#/definitions/KeywordStringType"
        },
        "VariableLevel2": {
          "$ref": "#/definitions/KeywordStringType"
        },
        "VariableLevel3": {
          "$ref": "#/definitions/KeywordStringType"
        },
        "DetailedVariable": {
          "$ref": "#/definitions/KeywordStringType"
        }
      },
      "required": ["Category", "Topic", "Term"]
    },
    "KeywordStringType": {
      "description": "The keyword string type for science keywords. The pattern below helps to minimize the types of characters allowed in the keywords to help users minimize keyword issues.",
      "type": "string",
      "minLength": 1,
      "maxLength": 80,
      "pattern": "[\\w\\-&'()\\[\\]/.\"#$%\\^@!*+=,][\\w\\-&'()\\[\\]/.\"#$%\\^@!*+=, ]{1,79}"
    },

    "MetadataSpecificationType": {
      "type": "object",
      "additionalProperties": false,
      "description": "This object requires any metadata record that is validated by this schema to provide information about the schema.",
      "properties": {
        "URL": {
          "description": "This element represents the URL where the schema lives. The schema can be downloaded.",
          "type": "string",
          "enum": ["https://cdn.earthdata.nasa.gov/generics/visualization/v1.0.0"]
        },
        "Name": {
          "description": "This element represents the name of the schema.",
          "type": "string",
          "enum": ["Visualization"]
        },
        "Version": {
          "description": "This element represents the version of the schema.",
          "type": "string",
          "enum": ["1.0.0"]
        }
      },
      "required": ["URL", "Name", "Version"]
    }
  }
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/visualization/v1.0.0/metadata.json
{
  "Identifier": "MODIS_Combined_L3_IGBP_Land_Cover_Type_Annual",
  "Name": "MODIS_Combined_L3_IGBP_Land_Cover_Type_Annual",

  "VisualizationType": "tiles",

  "Title": "Land Cover Type (L3, IGBP, Annual, Best Available, MODIS, Aqua+Terra)",

  "Subtitle": "Aqua+Terra MODIS",
  "Description": "The Terra and Aqua combined Moderate Resolution Imaging Spectroradiometer (MODIS) Land Cover Type (MCD12Q1) Version 6 data product provides global land cover types at yearly intervals. The MCD12Q1 Version 6 data product is derived using supervised classifications of MODIS Terra and Aqua reflectance data. The supervised classifications then undergo additional post-processing that incorporate prior knowledge and ancillary information to further refine specific classes. This layer defines land cover type based on the International Geosphere-Biosphere Programme (IGBP) classification scheme. The classification legend and class descriptions are listed in section 5 of the User Guide",

  "ScienceKeywords": [
    {
      "Category": "EARTH SCIENCE",
      "Topic": "SPECTRAL/ENGINEERING",
      "Term": "tbd",
      "VariableLevel1": "tbd",
      "DetailedVariable": "tbd"
    },
    {
      "Category": "EARTH SCIENCE SERVICES",
      "Topic": "DATA ANALYSIS AND VISUALIZATION",
      "Term": "DATA VISUALIZATION",
      "VariableLevel1": "tbd"
    }
  ],

  "TemporalExtents": [
    {
      "RangeDateTimes": [
        {
          "BeginningDateTime": "2001-01-01T00:00:00.000Z",
          "EndingDateTime": "2019-12-31T23:59:59.999Z"
        }
      ]
    }
  ],

  "What": {

  "SupportsContinuousBrowsing": false,

  "Dimension": {
    "Current": "false",
    "Default": "2018-01-01",
    "Value": "2001-01-01/2018-01-01/P1Y",
    "ows:Identifier": "Time",
    "ows:UOM": "ISO8601"
  },
  "Format": "image/png",
  "ResourceURL": {
    "format": "image/png",
    "resourceType": "tile",
    "template": "https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/MODIS_Combined_L3_IGBP_Land_Cover_Type_Annual/default/{Time}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.png"
  },
  "LegendURL": [
    {
      "format": "image/svg+xml",
      "height": "288",
      "width": "288",
      "xlink:href": "https://gibs.earthdata.nasa.gov/legends/MODIS_IGBP_Land_Cover_Type_V.svg",
      "@xlink:role": "http://earthdata.nasa.gov/gibs/legend-type/vertical",
      "@xlink:title": "GIBS Color Map Legend: Vertical",
      "@xlink:type": "simple"
    },
    { "@format": "image/svg+xml",
      "@height": "270",
      "@width": "270",
      "@xlink:href": "https://gibs.earthdata.nasa.gov/legends/MODIS_IGBP_Land_Cover_Type_H.svg",
      "@xlink:role": "http://earthdata.nasa.gov/gibs/legend-type/horizontal",
      "@xlink:title": "GIBS Color Map Legend: Horizontal",
      "@xlink:type": "simple"
    }
  ],
  "Metadata": [
    {
      "@xlink:href": "https://gibs.earthdata.nasa.gov/colormaps/v1.3/MODIS_IGBP_Land_Cover_Type.xml",
      "@xlink:role": "http://earthdata.nasa.gov/gibs/metadata-type/colormap",
      "@xlink:title": "GIBS Color Map: Data - RGB Mapping",
      "@xlink:type": "simple"
    },
    {
      "@xlink:href": "https://gibs.earthdata.nasa.gov/colormaps/v1.0/MODIS_IGBP_Land_Cover_Type.xml",
      "@xlink:role": "http://earthdata.nasa.gov/gibs/metadata-type/colormap/1.0",
      "@xlink:title": "GIBS Color Map: Data - RGB Mapping",
      "@xlink:type": "simple"
    },
    {
      "@xlink:href": "https://gibs.earthdata.nasa.gov/colormaps/v1.3/MODIS_IGBP_Land_Cover_Type.xml",
      "@xlink:role": "http://earthdata.nasa.gov/gibs/metadata-type/colormap/1.3",
      "@xlink:title": "GIBS Color Map: Data - RGB Mapping",
      "@xlink:type": "simple"
    }
  ],
  "TileMatrixSetLink":
  {
    "TileMatrixSet": "500m"
  },
  "WGS84BoundingBox": {
    "crs": "urn:ogc:def:crs:OGC:2:84",
    "LowerCorner": [-180, -90],
    "UpperCorner": [180, 90]
  },

  "Ongoing": false,
  "measurement": "Land Cover",
  "RetentionPeriod": -1,
  "daynight": [
    "day"
  ],
  "layerPeriod": "Yearly"

  },

  "How": {
  },

  "ConceptIds": [
    {
      "type": "STD",
      "value": "C186286578-LPDAAC_ECS",
      "shortName": "MCD12Q1",
      "title": "MODIS/Terra+Aqua Land Cover Type Yearly L3 Global 500m SIN Grid V006",
      "version": "006",
      "dataCenter": "LPDAAC_ECS"
    }
  ],

  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generics/visualization/v1.0.0",
    "Name": "Visualization",
    "Version": "1.0.0"
  }
}
