=== nasa/Common-Metadata-Repository/schemas/resources/schemas/index/v0.0.1/schema.json
{
   "$id": "https://earthdata.nasa.gov/schema/generics/index",
   "$schema": "http://json-schema.org/draft-07/schema#",
   "title": "Generic-Index",
   "description": "This scheme defines how index configurations are to be defined. These index definitions support both Elastic and Graph-DB",
   "type": "object",
   "additionalProperties": false,
   "properties": {
        "MetadataSpecification": {
            "description": "Contains several fields to define the specifics of the grid",
            "$ref": "#/definitions/MetadataSpecificationType"},
        "SubConceptType": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4
        },
        "Generic": {"$ref": "#/definitions/GenericType"},
        "IndexSetup" : {
          "description": "Contains fields for index level configurations in Elastic",
          "$ref": "#/definitions/IndexSetupType"
        },
        "Indexes": {
            "type": "array",
            "uniqueItems": true,
            "minItems": 1,
            "items": {"$ref": "#/definitions/IndexType"}
        }
    },
    "required": ["MetadataSpecification", "Generic"],
    "definitions": {
        "MetadataSpecificationType": {
            "type": "object",
            "additionalProperties": false,
            "description": "This object requires any metadata record that is validated by this schema to provide information about the schema.",
            "properties": {
                "URL": {
                    "description": "This element represents the URL where the schema lives. The schema can be downloaded.",
                    "type": "string",
                    "const": "https://cdn.earthdata.nasa.gov/generic/index/v0.0.1"
                },
                "Name": {
                    "description": "This element represents the name of the schema.",
                    "type": "string",
                    "const": "Generic-Index"
                },
                "Version": {
                    "description": "This element represents the version of the schema.",
                    "type": "string",
                    "const": "0.0.1"
                }
            },
            "required": ["URL", "Name", "Version"]
        },
        "GenericType": {
          "type": "object",
          "additionalProperties": false,
          "Description": "The matching schema for this index configuration",
          "properties": {
            "Name": {"type": "string"},
            "Version": {"type": "string"}
          },
          "required": ["Name", "Version"]
        },
        "IndexSetupType": {
          "type": "object",
          "additionalProperties": false,
          "Description": "Define Elastic configurations for the entire index",
          "properties": {
            "index" : {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "number_of_shards" : {
                  "type": "number",
                  "minimum": 1,
                  "maximum": 32
                },
                "number_of_replicas" : {
                  "type": "number",
                  "minimum": 1,
                  "maximum": 32
                },
                "refresh_interval" : {
                  "type": "string",
                  "pattern": "[0-9]+s"}
              }
            }
          }
        },
        "IndexType": {
            "$comment": "This object is subject to major change",
            "type": "object",
            "additionalProperties": false,
            "description": "Define one index that needs to be created",
            "properties": {
                "Description": {
                    "description": "Note about the setting",
                    "type": "string",
                    "minLength": 1
                },
                "Field": {
                    "description": "The Field to index, defined as a jq style path",
                    "type": "string",
                    "examples": [".RootElement.SubElement"],
                    "minLength": 1
                },
                "Mapping": {
                  "description": "The data format to map this index to",
                  "type": "string",
                  "default": "string",
                  "enum": ["string", "int", "date"]
                },
                "Type": {
                    "description": "target index software to host the index",
                    "type": "string",
                    "enum": ["elastic", "graph"],
                    "default": "elastic"
                },
                "Name": {
                    "description": "The name to give the index within the index server",
                    "type": "string",
                    "minLength": 1
                },
                "Indexer": {
                    "description": "The name of the function in code that will generate the index for this field",
                    "type": "string",
                    "minLength": 1
                },
                "Configuration": {
                    "decription": "Any valid JSON can be defined here and it will be passed to the indexer as a configuration for this specific index",
                    "additionalProperties": true
                }
            },
            "required": ["Field", "Name"]
        }
    }
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/order-option/v1.0.0/index.json
{
  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generic/index/v0.0.1",
    "Name": "Generic-Index",
    "Version": "0.0.1"
  },
  "Generic": {
    "Name": "Order Option",
    "Version": "1.0.0"
  },
  "SubConceptType": "OO",
  "Indexes":
  [
    {
      "Description": "Name",
      "Field": ".Name",
      "Name": "Name",
      "Mapping": "string"
    }, {
      "Description": "Id - This is the old ECHO 10 GUID.",
      "Field": ".Id",
      "Name": "Id",
      "Mapping": "string"
    }
  ]
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/service-entry/v1.0.0/index.json
{
  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generic/index/v0.0.1",
    "Name": "Generic-Index",
    "Version": "0.0.1"
  },
  "Generic": {
    "Name": "Service Entry",
    "Version": "1.0.0"
  },
  "SubConceptType": "SE",
  "Indexes":
  [
    {
      "Description": "Name",
      "Field": ".Name",
      "Name": "Name",
      "Mapping": "string"
    }, {
      "Description": "Id - This is the old ECHO 10 GUID.",
      "Field": ".Id",
      "Name": "Id",
      "Mapping": "string"
    }
  ]
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/visualization/v1.0.0/index.json
{
  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generic/index/v0.0.1",
    "Name": "Generic-Index",
    "Version": "0.0.1"
  },
  "Generic": {
    "Name": "Visualization",
    "Version": "1.0.0"
  },
  "SubConceptType": "VIS",
  "IndexSetup" : {
    "index": {
      "number_of_shards": 3,
      "number_of_replicas": 1,
      "refresh_interval": "1s"
    }
  },
  "Indexes":
  [
    {
      "Description": "Identifier",
      "Field": ".Identifier",
      "Name": "Id",
      "Mapping": "string"
    },
    {
      "Description": "Identifier",
      "Field": ".Identifier",
      "Name": "Identifier",
      "Mapping": "string"
    },
    {
      "Description": "Schema Name as the Name field",
      "Field": ".Name",
      "Name": "Name",
      "Mapping": "string"
    },
    {
      "Description": "Schema Title as the Title field",
      "Field": ".Title",
      "Name": "Title",
      "Mapping": "string"
    },
    {
      "Description": "VisualizationType",
      "Field": ".VisualizationType",
      "Name": "Visualization-Type",
      "Mapping": "string"
    },
    {    
      "Description": "Visualization Source ConceptIds",
      "Field": ".ConceptIds",
      "Name": "Concept-Ids",
      "Mapping": "string",
      "Indexer": "simple-array-field",
      "Configuration": {"sub-fields": ["value", "shortName"]}
    },
    {    
      "Description": "Visualization Source ConceptIds in keywords",
      "Field": ".ConceptIds",
      "Name": "keyword",
      "Mapping": "string",
      "Indexer": "simple-array-field",
      "Configuration": {"sub-fields": ["value"]}
    },
    {
      "Description": "Identifier with the keywords",
      "Field": ".Identifier",
      "Name": "keyword",
      "Mapping": "string"
    }
  ]
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/grid/v0.0.1/index.json
{
  "MetadataSpecification": {
      "URL": "https://cdn.earthdata.nasa.gov/generic/index/v0.0.1",
      "Name": "Generic-Index",
      "Version": "0.0.1"
  },
    "Generic": {
      "Name": "Grid",
      "Version": "0.0.1"
    },
  "SubConceptType": "GRD",
  "Indexes":
  [
    {
       "Description": "Name",
       "Field": ".Name",
       "Name": "Name",
       "Mapping": "string"
    },
    {
      "Description": "Long Name",
      "Field": ".LongName",
      "Name": "Long-Name",
      "Mapping": "string"
    },
    {
      "Description": "Description of the Grid",
      "Field": ".Description",
      "Name": "Description",
      "Mapping": "string"
    },
    {
      "Description": "Coordinate Reference System Type",
      "Field": ".GridDefinition.CoordinateReferenceSystemID.Type",
      "Name": "CoordinateReferenceSystemID-Type",
      "Mapping": "string"
    },
    {
      "Description": "Coordinate Reference System Code",
      "Field": ".GridDefinition.CoordinateReferenceSystemID.Code",
      "Name": "CoordinateReferenceSystemID-Code",
      "Mapping": "string"
    },
    {
      "Description": "Coordinate Reference System Title",
      "Field": ".GridDefinition.CoordinateReferenceSystemID.Title",
      "Name": "CoordinateReferenceSystemID-Title",
      "Mapping": "string"
    },
    {
      "Description": "Coordinate Reference System URL",
      "Field": ".GridDefinition.CoordinateReferenceSystemID.URL",
      "Name": "CoordinateReferenceSystemID-URL",
      "Mapping": "string"
    },
    {
      "Description": "Coordinate Reference System",
      "Field": ".GridDefinition.CoordinateReferenceSystemID",
      "Name": "CoordinateReferenceSystem",
      "Mapping": "string",
      "Indexer": "complex-field",
      "Configuration": {"sub-fields": ["Type", "Code", "Title", "URL"]}
    },
    {
      "Description": "Mock index for property field",
      "Field": ".Name",
      "Name": "Name",
      "Type": "graph",
      "Indexer": "property"
  },
  {
      "Description": "Mock index for property field",
      "Field": ".Version",
      "Name": "Version",
      "Type": "graph",
      "Indexer": "property"
  },
  {
      "Description": "Mock index for separate entity field",
      "Field": ".GridDefinition.CoordinateReferenceSystemID",
      "Name": "CoordinateReferenceSystem",
      "Type": "graph",
      "Indexer": "separate-node",
      "Configuration": {
          "properties": ["Type", "URL"],
          "relationship": "DefinedBy"
          }
  },
  {
      "Description": "Mock index for separate entity field",
      "Field": ".Organization",
      "Name": "Organization",
      "Type": "graph",
      "Indexer": "separate-node",
      "Configuration": {
          "properties": ["ShortName"],
          "relationship": "PublishedBy"
          }
  },
  {
      "Description": "Mock index for separate entity field",
      "Field": ".RelatedURLs",
      "Name": "URL",
      "Type": "graph",
      "Indexer": "separate-node",
      "Configuration": {
          "properties": ["URL", "URLContentType"],
          "relationship": "RelatedTo"
          }
  }
  ]
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/data-quality-summary/v1.0.0/index.json
{
  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generic/index/v0.0.1",
    "Name": "Generic-Index",
    "Version": "0.0.1"
  },
  "Generic": {
    "Name": "Data Quality Summary",
    "Version": "1.0.0"
  },
  "SubConceptType": "DQS",
  "IndexSetup" : {
    "index": {
      "number_of_shards": 3,
      "number_of_replicas": 1,
      "refresh_interval": "1s"
    }
  },
  "Indexes":
  [
    {
      "Description": "Name",
      "Field": ".Name",
      "Name": "Name",
      "Mapping": "string"
    },
    {
      "Description": "Id - This is the old ECHO 10 GUID.",
      "Field": ".Id",
      "Name": "Id",
      "Mapping": "string"
    }
  ]
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/visualization-draft/v1.1.0/index.json
{
  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generic/index/v0.0.1",
    "Name": "Generic-Index",
    "Version": "0.0.1"
  },
  "Generic": {
    "Name": "Visualization Draft",
    "Version": "1.1.0"
  },
  "SubConceptType": "VISD",
  "IndexSetup" : {
    "index": {
      "number_of_shards": 3,
      "number_of_replicas": 1,
      "refresh_interval": "1s"
    }
  },
  "Indexes":
  [
    {
      "Description": "Draft Visualization Short Name",
      "Field": ".Name",
      "Name": "name",
      "Mapping": "string"
    }
  ]
}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/service-option/v1.0.0/index.json
{
  "MetadataSpecification": {
    "URL": "https://cdn.earthdata.nasa.gov/generic/index/v0.0.1",
    "Name": "Generic-Index",
    "Version": "0.0.1"
  },
  "Generic": {
    "Name": "Service Option",
    "Version": "1.0.0"
  },
  "SubConceptType": "SO",
  "Indexes":
  [
    {
      "Description": "Name",
      "Field": ".Name",
      "Name": "Name",
      "Mapping": "string"
    }, {
      "Description": "Id - This is the old ECHO 10 GUID.",
      "Field": ".Id",
      "Name": "Id",
      "Mapping": "string"
    }
  ]
}
