=== nasa/Common-Metadata-Repository/schemas/resources/schemas/visualization/v1.1.0/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "UMM-Vis",
  "type": "object",
  "$comment": "set the following as false to enforce",
  "additionalProperties": false,
  "properties": {
    "Identifier": {
      "description": "The unique identifier for the visualization.",
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },
    "Name": {
      "$comment": "This field is added by CMR team. Need to clarify.",
      "description": "A name of the visualization.",
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },
    "Title": {
      "description": "A short descriptive title of the visualization.",
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },
    "Subtitle": {
      "description": "A short descriptive subtitle of the visualization.",
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },
    "Description": {
      "description": "A human readable description of the visualization written using HTML notation for advanced text.  The goal is to create descriptions for the science-minded public that may have an interest in finding out what the visualization shows, why itâ€™s important, how it was created, etc...",
      "type": "string",
      "minLength": 1,
      "maxLength": 1024
    },
    "ScienceKeywords": {
      "description": "Earth Science keywords that are representative of the data being visualized. The controlled vocabulary for Science Keywords is maintained in the Keyword Management System (KMS).",
      "type": "array",
      "items": {
        "$ref": "definitions.json#/definitions/ScienceKeywordType"
      },
      "minItems": 0
    },
    "SpatialExtent": {
      "$comment": "this one probably should be array, in order to handle case of discrete areas",
      "$ref": "definitions.json#/definitions/SpatialExtentType"
    },
    "TemporalExtents": {
      "description": "This class contains attributes which describe the temporal range of a specific layer. Temporal Extent includes a specification of the Temporal Range Type of the collection, which is one of Range Date Time, Single Date Time, or Periodic Date Time",
      "type": "array",
      "items": {
        "$ref": "definitions.json#/definitions/TemporalExtentType"
      },
      "minItems": 1
    },
    "ConceptIds": {
      "description": "Which CMR dataset(s) are represented by the visualization.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Type": {
            "description": "Identify whether the associated dataset is NRT or STD.",
            "type": "string",
            "enum": [
              "NRT",
              "STD"
            ]
          },
          "Value": {
            "description": "The dataset's CMR concept id",
            "type": "string"
          },
          "DataCenter": {
            "type": "string"
          },
          "ShortName": {
            "type": "string"
          },
          "Title": {
            "type": "string"
          },
          "Version": {
            "type": "string"
          }
        },
        "required": ["Type", "Value"],
        "additionalProperties": false
      },
      "minItems": 1
    },

    "VisualizationType": {
      "type": "string",
      "enum": ["tiles", "maps"]
    },

    "Specification": {
      "$comment": "must be here when additionalProperties==false. otherwise fails"
    },

    "Generation": {
      "$comment": "must be here when additionalProperties==false. otherwise fails"
    },

    "MetadataSpecification": {
      "description": "Required to add in schema information into every record. It includes the schema's name, version, and URL location. The information is controlled through enumerations at the end of this schema.",
      "$ref": "definitions.json#/definitions/MetadataSpecificationType"
    }

  },

  "required": [
    "Identifier",
    "VisualizationType",
    "Name",
    "Specification",
    "Generation",
    "ConceptIds",
    "MetadataSpecification"
  ],
  "allOf": [
    {
      "if": {
        "properties": {
          "VisualizationType": {"const": "tiles"}
        }
      },
      "then": {
        "properties": {
          "Specification": {
            "$ref": "tiles/schema.json#/properties/Specification"
          },
          "Generation": {
            "$ref": "tiles/schema.json#/properties/Generation"
          }
        }
      }
    },

    {
      "if": {
        "properties": {
          "VisualizationType": {"const": "maps"}
        }
      },
      "then": {
        "properties": {
          "Specification": {
            "$ref": "maps/schema.json#/properties/Specification"
          },
          "Generation": {
            "$ref": "maps/schema.json#/properties/Generation"
          }
        }
      }
    }

  ]

}

=== nasa/Common-Metadata-Repository/schemas/resources/schemas/visualization/v1.1.0/metadata.json
{
    "Identifier": "OPERA_L3_DSWX-HLS_LL_v1_STD",
    "Name": "OPERA_L3_Dynamic_Surface_Water_Extent-HLS_v1_STD",
    "Title": "OPERA Dynamic Surface Water Extent (L3)",
    "Subtitle": "DSWx-HLS",
    "Description": "YET_TO_SUPPLY",
    "VisualizationType": "tiles",
    "ScienceKeywords": [
        {
            "Category": "EARTH SCIENCE",
            "Topic": "SPECTRAL/ENGINEERING",
            "Term": "tbd",
            "VariableLevel1": "tbd",
            "DetailedVariable": "tbd"
        },
        {
            "Category": "EARTH SCIENCE SERVICES",
            "Topic": "DATA ANALYSIS AND VISUALIZATION",
            "Term": "DATA VISUALIZATION",
            "VariableLevel1": "tbd"
        }
    ],
    "ConceptIds": [
        {
            "Type": "STD",
            "Value": "C2617126679-POCLOUD",
            "ShortName": "OPERA_L3_DSWX-HLS_V1",
            "Title": "OPERA Dynamic Surface Water Extent from Harmonized Landsat Sentinel-2 product (Version 1)",
            "Version": "1.0",
            "DataCenter": "POCLOUD"
        }
    ],
    "Specification": {
        "ProductIdentification": {
            "InternalIdentifier": "OPERA_L3_DSWX-HLS_LL_v1_STD",
            "StandardOrNRTExternalIdentifier": "OPERA_L3_Dynamic_Surface_Water_Extent-HLS_v1_STD",
            "BestAvailableExternalIdentifier": "OPERA_L3_Dynamic_Surface_Water_Extent-HLS",
            "GIBSTitle": "OPERA Dynamic Surface Water Extent (L3, DSWx-HLS)",
            "WorldviewTitle": "OPERA Dynamic Surface Water Extent (L3)",
            "WorldviewSubtitle": "DSWx-HLS"
        },
        "ProductMetadata": {
            "InternalIdentifier": "OPERA_L3_DSWX-HLS_LL_v1_STD",
            "SourceDatasets": [
                "C2617126679-POCLOUD"
            ],
            "RepresentingDatasets": [
                "C2617126679-POCLOUD"
            ],
            "ScienceParameters": [
                "dswx_hls"
            ],
            "ParameterUnits": [null],
            "Measurement": "Surface Water Extent",
            "GranuleOrComposite": "Granule",
            "DataDayBreak": "00:00:00Z",
            "VisualizationLatency": "1 day",
            "UpdateInterval": 1440,
            "TemporalCoverage": "2023-04-10/P1D",
            "WGS84SpatialCoverage": [
                -84.0,
                -180.0,
                84.0,
                180.0
            ],
            "NativeSpatialCoverage": [
                -84.0,
                -180.0,
                84.0,
                180.0
            ],
            "AscendingOrDescending": "N/A",
            "ColorMap": "colormap is embedded in the tif file",
            "Ongoing": true,
            "RetentionPeriod": -1,
            "Daynight": [
                "day"
            ],
            "OrbitTracks": [
                "OrbitTracks_Landsat-8_Descending",
                "OrbitTracks_Sentinel-2A_Descending",
                "OrbitTracks_Sentinel-2B_Descending"
            ],
            "OrbitDirection": [
                "descending"
            ],
            "LayerPeriod": "Daily",
            "ows:Identifier": "OPERA_L3_Dynamic_Surface_Water_Extent-HLS_v1_STD",
            "wmts:TileMatrixSetLink": {
                "TileMatrixSet": "31.25m"
            },
            "wmts:Dimension": {
                "Identifier": "Time",
                "UOM": "ISO8601",
                "Default": "2024-11-19",
                "Current": false,
                "Value": [
                    "2024-05-11/2024-06-02/P1D",
                    "2024-06-04/2024-11-19/P1D"
                ]
            },
            "wmts:Format": ["image/png"],
            "ows:Metadata": [
                {
                    "xlink:Href": "https://gitc.earthdata.nasa.gov/colormaps/v1.0/OPERA_Dynamic_Surface_Water_Extent.xml",
                    "xlink:Role": "http://earthdata.nasa.gov/gibs/metadata-type/colormap/1.0",
                    "xlink:Title": "GIBS Color Map: Data - RGB Mapping",
                    "xlink:Type": "simple"
                },
                {
                    "xlink:Href": "https://gitc.earthdata.nasa.gov/colormaps/v1.3/OPERA_Dynamic_Surface_Water_Extent.xml",
                    "xlink:Role": "http://earthdata.nasa.gov/gibs/metadata-type/colormap/1.3",
                    "xlink:Title": "GIBS Color Map: Data - RGB Mapping",
                    "xlink:Type": "simple"
                },
                {
                    "xlink:Href": "https://gitc.earthdata.nasa.gov/colormaps/v1.3/OPERA_Dynamic_Surface_Water_Extent.xml",
                    "xlink:Role": "http://earthdata.nasa.gov/gibs/metadata-type/colormap/",
                    "xlink:Title": "GIBS Color Map: Data - RGB Mapping",
                    "xlink:Type": "simple"
                }
            ]
        }
    },
    "Generation": {
        "SourceProjection": "EPSG:4326",
        "SourceResolution": "Native",
        "SourceFormat": "GeoTIFF",
        "SourceColorModel": "Indexed RGBA",
        "SourceCoverage": "Tiled",
        "OutputProjection": "EPSG:4326",
        "OutputResolution": "31.25m",
        "OutputFormat": "PPNG"
    },
    "MetadataSpecification": {
        "URL": "https://cdn.earthdata.nasa.gov/umm/visualization/v1.1.0",
        "Name": "Visualization",
        "Version": "1.1.0"
    }
}
